prod test
prod test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,10 +24,12 @@ jobs:
         sudo chmod +x /usr/local/bin/docker-compose
         docker-compose --version
 
-    - name: Run Docker Compose
+    # Entorno dev
+    - name: Run Docker Compose (dev environment)
+      if: github.ref == 'refs/heads/dev'
       run: |
-        export APP_VERSION=0.0.1
-        export STAGE=prod
+        export APP_VERSION=0.0.1-dev
+        export STAGE=dev
         export DB_PASSWORD=MySecr3tPassWord@as2
         export DB_NAME=TesloDB
         export DB_HOST=TesloDB
@@ -38,16 +40,96 @@ jobs:
         export JWT_SECRET=Est3EsMISE3Dsecreto32s
         docker-compose -f ./docker-compose.yml up -d
 
-    - name: Tear down Docker Compose
+    - name: Esperar a que el servicio esté disponible (dev)
+      if: github.ref == 'refs/heads/dev'
       run: |
-        export APP_VERSION=0.0.1
+        until curl -f http://localhost:3000/api; do
+          echo "Esperando a que el servicio dev esté disponible..."
+          sleep 5
+        done
+
+    - name: Ejecutar seed en la base de datos (dev)
+      if: github.ref == 'refs/heads/dev'
+      run: |
+        response=$(curl -s -X GET http://localhost:3000/api/seed)
+        echo "Seed response: $response"
+        if [[ "$response" != *"SEED EXECUTED"* ]]; then
+          echo "Error: Seed no se ejecutó correctamente en dev"
+          exit 1
+        fi
+
+    # Entorno qa
+    - name: Run Docker Compose (qa environment)
+      if: github.ref == 'refs/heads/qa'
+      run: |
+        export APP_VERSION=0.0.1-qa
+        export STAGE=qa
+        export DB_PASSWORD=MySecr3tPassWord@as2
+        export DB_NAME=TesloDB
+        export DB_HOST=TesloDB
+        export DB_PORT=5432
+        export DB_USERNAME=postgres
+        export PORT=4000
+        export HOST_API=http://localhost:4000/api
+        export JWT_SECRET=Est3EsMISE3Dsecreto32s
+        docker-compose -f ./docker-compose.yml up -d
+
+    - name: Esperar a que el servicio esté disponible (qa)
+      if: github.ref == 'refs/heads/qa'
+      run: |
+        until curl -f http://localhost:4000/api; do
+          echo "Esperando a que el servicio qa esté disponible..."
+          sleep 5
+        done
+
+    - name: Ejecutar seed en la base de datos (qa)
+      if: github.ref == 'refs/heads/qa'
+      run: |
+        response=$(curl -s -X GET http://localhost:4000/api/seed)
+        echo "Seed response: $response"
+        if [[ "$response" != *"SEED EXECUTED"* ]]; then
+          echo "Error: Seed no se ejecutó correctamente en qa"
+          exit 1
+        fi
+
+    # Entorno prod
+
+    - name: Run Docker Compose (qa environment)
+      if: github.ref == 'refs/heads/prod'
+      run: |
+        export APP_VERSION=0.0.1-prod
         export STAGE=prod
         export DB_PASSWORD=MySecr3tPassWord@as2
         export DB_NAME=TesloDB
         export DB_HOST=TesloDB
         export DB_PORT=5432
         export DB_USERNAME=postgres
-        export PORT=3000
-        export HOST_API=http://localhost:3000/api
+        export PORT=5000
+        export HOST_API=http://localhost:5000/api
         export JWT_SECRET=Est3EsMISE3Dsecreto32s
-        docker-compose -f ./docker-compose.yml down
+        docker-compose -f ./docker-compose.yml up -d
+
+    - name: Esperar a que el servicio esté disponible (prod)
+      if: github.ref == 'refs/heads/prod'
+      run: |
+        until curl -f http://localhost:5000/api; do
+          echo "Esperando a que el servicio qa esté disponible..."
+          sleep 5
+        done
+
+    - name: Ejecutar seed en la base de datos (prod)
+      if: github.ref == 'refs/heads/prod'
+      run: |
+        response=$(curl -s -X GET http://localhost:5000/api/seed)
+        echo "Seed response: $response"
+        if [[ "$response" != *"SEED EXECUTED"* ]]; then
+          echo "Error: Seed no se ejecutó correctamente en prod"
+          exit 1
+        fi
+      
+    
+
+    # Tear down solo en prod
+    - name: Tear down Docker Compose (prod)
+      if: github.ref == 'refs/heads/prod'
+      run: docker-compose -f ./docker-compose.yml down
